name: Build Android APK (Release)

on:
  push:
    tags:
      - 'v*' # Срабатывает только если вы создаете тег (например v1.0.0)
  workflow_dispatch: # Позволяет запустить кнопку вручную

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      # 1. Восстанавливаем .env файл
      - name: Create .env file
        run: |
          echo "${{ secrets.NEXT_PUBLIC_ENV }}" > .env.local

      # 2. Восстанавливаем google-services.json
      - name: Decode google-services.json
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: |
          echo "$GOOGLE_SERVICES_JSON" | base64 --decode > android/app/google-services.json

      # 3. Восстанавливаем Keystore файл
      - name: Decode Keystore
        env:
          ANDROID_KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
        run: |
          echo "$ANDROID_KEYSTORE_BASE64" | base64 --decode > android/app/release.keystore

      # 4. Установка зависимостей и сборка Next.js
      - name: Install Dependencies
        run: npm ci --legacy-peer-deps

      - name: Build Next.js App
        run: npm run buildwin # Ваша команда сборки

      # 5. Синхронизация Capacitor
      - name: Sync Capacitor
        run: npx cap sync android

      # 6. Сборка APK с подписью
      - name: Build Release APK
        working-directory: android
        env:
          RELEASE_STORE_FILE: release.keystore
          RELEASE_STORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          RELEASE_KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        run: |
          chmod +x gradlew
          ./gradlew assembleRelease

      # 7. Выгрузка APK в GitHub Artifacts
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Z-App-Release
          path: android/app/build/outputs/apk/release/app-release.apk